### PR TITLE
test-appliance: create 'overlay/large' config

### PR DESCRIPTION
**Pull request by edjee**
Currently the test overlay/001 does not run, because it requires
larger devices while the configuration sets up small devices only.

This patch adds 'overlay/large' config to let users run overlay/001.

Signed-off-by: Edward Hyunkoo Jee <edjee@google.com>

### CODE REVIEW

**Review by tytso — COMMENTED** [review]
There needs to be a default configuration no matter what.  We can create a large config, and we can make default be an alias for small, but we need to have default.

Default is what is used when someone types "gce-xfstests -c overlayfs -g quick".   If you have large, then you can run the command "gce-xfstests -c overlayfs/large -g quick".

**Comment by edjee** [comment]
Before this patch, only `ext4` and `xfs` have multiple cfg files. But they don't have `<FS>/cfg/default`. Instead they alias one of the cfg to "default", in `function test_name_alias()` in their `<FS>/config` files. Hence I just followed that in this patch.

(In this patch, the cfg "default" is renamed to "small". Instead, `test_name_alias()` maps "default" to "small")

Maybe I missed something or am misunderstanding Ted's comment?

**Comment by edjee** [comment]
ping (a gentle reminder)

**Comment by tytso** [comment]
The other way you can solve this problem is by defining test_name_alias in /root/fs/ext4/config:

    function test_name_alias()
    {
         case "$1" in
     	     default)	echo "4k" ;;
     	     *)		echo "$1" ;;
         esac
    }

**Pull request merged**
