### PR TITLE
Enable proxy usage

### PR DESCRIPTION
**Pull request by josefbacik**
This adds the ability for setup-buildchroot to use a proxy to update the packages in the chroot.  I've also added a little blurb to the documentation so the next poor guy doesn't take 3 hours trying to figure out how to make it all work.

### CODE REVIEW

**Review by tytso — APPROVED** [review]
I really do prefer the e-mail workflow, but I suppose we can try the cherry-pick and github comment approach.....

**Review by tytso — COMMENTED** [review]
One minor change.  I used:

test -z "${PROXY}" || export http_proxy=${PROXY}

so if PROXY is not set, we don't end up setting the http_proxy environment variable to a zero-length string.

**Comment by tytso** [comment]
Wow, the git hub commenting system really awful.  It's not at all clear which patch you're commenting on.   :-(

**Review by tytso — COMMENTED** [review]
I've cherry-picked "add information on using a proxy".

**Comment by tytso** [comment]
I've cherry-picked "setup mtab in chroot" and "fix use of backports".   The old backports code wasn't causing problems for me, but it's a good change, even though I plan to be dropping jessie support shortly.  (It's too hard to test both against jessie and stretch, so the jessie support was bound to bitroot eventually anyway.)

**Comment by josefbacik** [comment]
Sorry I was going to email these today since apparently every time I added patches it added them to the pull request too which is confusing.  I'll rebase and fixup and then email what's left over.

**Comment by tytso** [comment]
I never had a problem with the e2fsck erroring out, but the e2fsck error commit is also good, and cherry pick.

Also, the reason why btrfs-progs wasn't in the default package list was because we were grabbing them from the backports in jessie  ---- f2fs-tools didn't exist at all, and btrfs-progs in jessie was so ancient as to be unusuable on modern kernels.   When we moved to stretch, I forgot to add them to the xfstests-packages file.  I'll fix that in my tree.

Note that what I tend to do is to put bleeding-edge packages in the kvm-xfstests/test-appliance/debs directory.  These will get picked up automatically by "do-all" and that's why I've never needed an --extra-packages argument for do-all.     What I also tend to do when I drop in a bleeding edge e2fsprogs in the debs directory is I will put an e2fsprogs.ver file in the top-level directory of xfstests-bld, generated by e2fsprogs/util/get-ver.  It basically just runs this command:

ver=$(git describe --always --dirty); echo "e2fsprogs	$ver ($(git log -1 --pretty=%cD))"

This then gets picked up in the git-versions file so there is a record of exactly what components were used to run the tests.

**Comment by josefbacik** [comment]
Yeah I figured that's what you were doing, but I'm running this on a centos7 box with no easy way to generate .deb packages for the user space tools.  I'll look into adding stuff to build .deb packages from btrfs-prog's git so I can drop in new versions whenever I want.  Having --extra-packages is good for when people don't care about trying new stuff, just getting whatever tool they need into place.

**Comment by tytso** [comment]
If you can run setup-buildchroot on centos7, building the debian package in the build chroot should be pretty simple.   I know, because I've been building btrfs-progs for backports.  :-)

I haven't done it for stretch-backports yet because the rule is you can't build for stretch-backports until it shows up in the buster (the new Debian testing) release, and there hasn't been a new btrfs-progs landing in Debian testing, at least not the last time I've looked.

**Pull request closed without merging**
